### ISSUE TITLE
[Data browser] "Copy to clipboard" button does not work properly

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#102]
## Purpose
Bug report

## Description
"Copy to clipboard" button does not work properly

## Screenshot or video
![CopyToClipboadrNotWork](https://user-images.githubusercontent.com/72174933/147449912-435ef736-2374-436b-8a7b-c7023785cc68.gif)

## See also
https://github.com/mac-s-g/react-json-view/issues/161

**Comment by d-hayashi** [comment]
copy to clipboard を無効化する
