### ISSUE TITLE
[User manager] Show database name in selector of database when editing role

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#103]
## Purpose
Feature request

## Description
Role 編集時に，データベース ID だけじゃなくてデータベース名も一緒に表示されている方が分かりやすい

**Comment by d-hayashi** [comment]
工数を要調査

**Comment by d-hayashi** [comment]
(参考)
https://github.com/dataware-tools/app-user-manager/blob/81872b7fc0ebe1847484b9cc0067a90b67c513c9/src/components/organisms/PermissionListItem.tsx#L51
