### ISSUE TITLE
[Data browser, User manager] Fix UX of editing settings

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#104]
## Purpose
Feature request

## Description
モーダル上で何かを編集する操作が多いが、モーダルの外側をクリックしたら閉じるようになってるので、操作を若干慎重にしなければならないのが嬉しくない

## TODO

- [x] DataBrowser
- [x] UserManager

**Comment by d-hayashi** [comment]
選択肢:  
1. モーダルの外側をクリックしても閉じない様にする
2. モーダル内で変更があったら外側をクリックしたときに確認ダイアログを表示する
3. ローカルストレージに保存して復旧できるようにする
4. モーダルをやめてページにする
