### ISSUE TITLE
[Data browser] Using <input type="number"/> for input box of number type column is not best choice

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#105]
## Purpose
Feature request

## Description
<input type="number/> はとりあえず数値入力用に使える性能をしていないので，より望ましい実装に置き換えるべき

## See also
https://note.com/takamoso/n/n79df2d8f16bf

**Comment by d-hayashi** [comment]
↓のように patter オプションを使ってみる？
`<input pattern="^-?\d{1,}\.\d*$" />`

(参考) https://qiita.com/ka215/items/795a179041c705bef03b
