### ISSUE TITLE
[Data browser] Preview supported file extensions should be shown when previewing file is not supported

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#107]
## Purpose
Feature request

## Description
プレビューをサポートされていないファイルをプレビューしている時，現在プレビューがサポートされているファイル拡張子一覧を表示するべき
それが示されているドキュメントのリンクでもOK

**Comment by d-hayashi** [comment]
https://github.com/dataware-tools/app-data-browser-next/blob/master/src/components/molecules/FilePreviewer/DefaultPreviewer.tsx
DefaultPreviewer の表示をもう少し親切にする. 
- ドキュメントへのリンクを貼る
