### ISSUE TITLE
[api-meta-store] Record is updated unexpectedly

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#111]
## Purpose
Bug? report

## Description
A と B というカラムが存在する DB の `/record` エンドポイントに `{A: "something"}` を POST して，そのレコードを GET すると `{A: "something", B: null}` が返ってくる
この GET した値をそのまま PATCH して，そのレコードを GET すると GET すると {A: "anything", B: "None"} になる 

## video
https://github.com/dataware-tools/app-data-browser-next/pull/331 がマージされると DataBrowser 上でこのバグが分かりやすくなる
![APIBugOnDataBrowser](https://user-images.githubusercontent.com/72174933/148504867-074591f9-60e1-4672-8117-bb9952490be3.gif)

**Comment by d-hayashi** [comment]
This bug is fixed in `pydtk>=0.1.10`, but api-meta-store v0.5.1 uses `pydtk==0.1.9`
