### ISSUE TITLE
[Data browser] Number and Datetime can't  be changed to empty 

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#112]
## Purpose
Bug report

## Description
Number と Datatime 型を，空でない値から空にできない
フロント側で，カラムが空文字だったら null に変換してバックエンドに送るようにすべき？

## Screenshot or video
![NumberDatetimeCantBeChangedToEmpty](https://user-images.githubusercontent.com/72174933/148522500-30f6474c-29a0-4103-b31f-f8cb6571f918.gif)

**Comment by d-hayashi** [comment]
バックエンド側は空文字では受け付けない仕様になってしまっているので、フロント側でnullにするのが手っ取り早いかと思います
