### ISSUE TITLE
[Data browser] Error should be reset when modal is closed

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#113]
## Purpose
Bug report

## Description
レコード追加時や編集時など，モーダルが閉じてもエラーがリセットされないことが多い
エラーをリセットして，すぐに再チャレンジできた方が使い勝手はよさそう

## Screenshot or video
![ErrorIsNotReset](https://user-images.githubusercontent.com/72174933/148523772-efcaba8e-6d19-4a2b-a37a-66f6fe355a5f.gif)

**Comment by d-hayashi** [comment]
By using Toast, this problem will be solved.  
Closing in favor of #68
