### ISSUE TITLE
[DataBrowser, UserManager] Confirm dialog should be shown when "onbeforeunload" event occur

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#117]
## Purpose
Feature request

## Description
レコードの編集/追加中などにウィンドウが閉じられようとしたら，確認用のダイアログが出るようになって欲しい

## See also
https://developer.mozilla.org/ja/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by d-hayashi** [comment]
メタ情報の編集中にウィンドウを閉じようとしたら確認ダイアログを出すようにしましょう
