### ISSUE TITLE
Repository named like "app-foobar" should be organized to monorepo?

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#123]
## Purpose
- Question / discussion

## Description
フロントエンドアプリ用のレポジトリはテンプレートから作られていて、開発用のツールの多くを共通している
そのため、開発用のツールをアップデートするときに同じことを別のリポジトリに適用しなきゃいけないことが多くて面倒
そういった点はモノレポにすると解消されるはずだが、多分モノレポの運用もそれはそれで面倒なので考えどころ

**Comment by d-hayashi** [comment]
今後長期的に考えていきましょう

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi @yusukefs 僕の中では、開発ツールを dev-tools-for-apps にまとめる方向性で解決したと認識してるんですが、合ってますか...？

**Comment by d-hayashi** [comment]
同じ認識です！

**Comment by d-hayashi** [comment]
Instead of creating a monorepo, we have decided to define commonly appearing dependencies in [dataware-tools/dev-tools-for-apps](https://github.com/dataware-tools/dev-tools-for-apps) and import the package in each app.
