### ISSUE TITLE
UI を個別にインポートできるようにする

### ISSUE THREAD

**Issue by yuri-sakai** [dataware-tools/dataware-tools#15]
UI を個別にインポートできるようにする
P4

**Comment by d-hayashi** [comment]
Closing in favor of #73

**Comment by hdl-service** [comment]
@d-hayashi: Closing this issue.

<details>

In response to [this](https://github.com/dataware-tools/dataware-tools/issues/15#issuecomment-903556958):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
