### ISSUE TITLE
[api-*] Kubernetesが指定する環境変数を使ってサービスのURLを指定する

### ISSUE THREAD

**Issue by yuri-sakai** [dataware-tools/dataware-tools#23]
[api-*] Kubernetesが指定する環境変数を使ってサービスのURLを指定する

# 概要

Kubernetes側が `<サービス名>_HOST` とか `<サービス名>_PORT` などの環境変数にサービスのIPアドレスを入れてくれてるので、それを使ってサービスのURLを読み込む様にする
P3

**Comment by d-hayashi** [comment]
↓環境変数を使っている部分
- https://github.com/dataware-tools/api-file-provider/blob/96956121b93088bc510559b7ee21a5d43a23cfb1/api/settings.py#L11
