### ISSUE TITLE
COMFIRMでなくDELETEのほうが良い

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/dataware-tools#27]
COMFIRMでなくDELETEのほうが良い
色は赤がよく使われているので赤を検討したほうがいいと思います

<img width="656" alt="スクリーンショット 2021-07-02 12 33 35" src="https://user-images.githubusercontent.com/61043090/124219131-a3567000-db36-11eb-8c1d-537aa13e2b4d.png">

例）
![image](https://user-images.githubusercontent.com/61043090/124220341-afdbc800-db38-11eb-87ee-e8b23c7bb077.png)

_Originally posted by @yuri-sakai in https://github.com/dataware-tools/dataware-tools/issues/2#issuecomment-872697950_

**Comment by yusukefs** [comment]
data-browserに適用する必要あり
