### ISSUE TITLE
権限がAdminなのにデータベースを閲覧できない

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/dataware-tools#3]
権限がAdminなのにデータベースを閲覧できない
```
Error
{"url":"/api/latest/meta_store/databases/default/records?per_page=20&page=1&search=&search_key=record_id","status":403,"statusText":"","body":{"detail":"Action \"metadata:read:public\" is not allowed on database \"default\""}}
please reload this page
```
<img width="1392" alt="スクリーンショット 2021-07-02 12 12 34" src="https://user-images.githubusercontent.com/22779813/124215358-cf6df300-db2e-11eb-8e3e-e79f81d98a8b.png">

_Originally posted by @kan-bayashi in https://github.com/dataware-tools/dataware-tools/issues/2#issuecomment-872680882_

**Comment by WatanabeToshimitsu** [comment]
Related https://github.com/dataware-tools/dataware-tools/issues/35
