### ISSUE TITLE
[Data browser] Support for specifying `base_dir_path` on each database

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/dataware-tools#42]
## Purpose
Feature request

## Description
データベースごとに `base_dir_path` を指定できるようにしたい

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi 
この issue って，pydtk 自体にデータベース毎に base_dir_path を分ける機能をつけて，それを data-browser からも設定できるようにしたい，という話で合ってますか？

**Comment by d-hayashi** [comment]
確か pydtk の DBHandler を初期化するときの base_dir_path をデータベースごとに指定できるようにしたいみたいな話だったと思うんですが、あまり使用用途が無い気がするので対応不要なのではと思います
