### ISSUE TITLE
ユーザ一覧で権限ごとに色をつけられると識別しやすくて良い

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/dataware-tools#5]
ユーザ一覧で権限ごとに色をつけられると識別しやすくて良い

<img width="507" alt="スクリーンショット 2021-07-02 12 05 38" src="https://user-images.githubusercontent.com/13210107/124216198-a2224480-db30-11eb-8a4e-429c7b0553ea.png">

イメージ：Notion

<img width="451" alt="スクリーンショット 2021-07-02 12 26 10" src="https://user-images.githubusercontent.com/13210107/124216229-b6fed800-db30-11eb-9670-43ff2f05db46.png">

_Originally posted by @yusukefs in https://github.com/dataware-tools/dataware-tools/issues/2#issuecomment-872685217_

**Comment by WatanabeToshimitsu** [comment]
Use Manager のこの UI は app-common の MultiSelect をそのまま使っているので、そこから書き換える必要がある
MultiSelect 自体は MUI の Autocompleteに依存していてるので、コードを見て実現できるかを確認する
確認取れてからバックエンドと共に実装に入る

**Comment by onose004** [comment]
> Role の ID や名前に基づいて色を指定してしまう

こちらの方式で、DBから取得したラベル名に対して、ローカル側で色を反映するようにしてみたのですが、どうでしょうか？
ユーザが変更することはできなくなりますが、DB側の変更はしなくて済むかと思います。

<img width="671" alt="スクリーンショット 2022-06-03 9 39 29" src="https://user-images.githubusercontent.com/8692594/171762873-c1dffa15-cc67-4d40-9afa-984acb7bcdd2.png">

**Comment by onose004** [comment]
User Role の文字列のハッシュ値から自動的に適当な色をつけられるような実装にしてみました。
実装はできましたが、新しい props を入れたのに伴い tsc が通らなくなってしまったので、型周り修正途中です。

<img width="689" alt="スクリーンショット 2022-06-10 18 14 56" src="https://user-images.githubusercontent.com/8692594/173033712-e58f29b4-95d0-479f-a05c-9f17fc2b09b3.png">

**Comment by WatanabeToshimitsu** [comment]
Resolved by https://github.com/dataware-tools/app-user-manager/pull/366
