### ISSUE TITLE
PyDTKで登録したデータがPyDTK経由では見れるのにData-browserからは見れない

### ISSUE THREAD

**Issue by kan-bayashi** [dataware-tools/dataware-tools#50]
## Purpose

- bug report 

## Description

```bash
$ cat metadata.json | pydtk db add file --database_id=test
$ pydtk db get file --database_id=test --parsable  # 見える
```

Databrowser上ではエントリが見えない
<img width="1163" alt="スクリーンショット 2021-07-15 12 08 18" src="https://user-images.githubusercontent.com/22779813/125721696-24c163cd-29b7-477c-80e7-8fb1d7ec075a.png">

**Comment by d-hayashi** [comment]
`record_id` に数字しか入っていない場合、 `handler.read(pql='("record_id" == regex(".*.*"))')` の `regex()` に引っかからないため何も出力されないのが原因の模様

**Comment by kan-bayashi** [comment]
<img width="1199" alt="スクリーンショット 2021-07-15 15 44 19" src="https://user-images.githubusercontent.com/22779813/125741503-3710134f-ddd5-45ef-877a-465b5ed87dc9.png">
一覧には出るようになったが、詳細画面でエラーとなる

**Comment by d-hayashi** [comment]
record_id が実際にDBに入ってるものとここに出てきているもので若干違ってると思うのですが、入れ直したりした覚えあります？

**Comment by kan-bayashi** [comment]
`database_id=debug` で再度登録したが再現しました
```bash
$ pydtk model generate metadata --record_id=11111111 --from_file test.csv | pydtk db add file --database_id=debug
```

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi これは修正済みですか？

**Comment by d-hayashi** [comment]
まだ修正できてないです（toolkit側は修正したけど api-meta-store でバージョンを上げてない状態)

**Comment by WatanabeToshimitsu** [comment]
なるほど Close し忘れでないならよかったです！
