### ISSUE TITLE
[Launcher] Recreate app-launcher

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#57]
## Purpose
- feature request

## Description
- デザインを統一するために Material-UI のコンポーネントで作り直したい
- 色々整備したので，[app-template-nextjs](https://github.com/dataware-tools/app-template-nextjs) を元にできると嬉しい

**Comment by d-hayashi** [comment]
新しい Launcher ではアプリ一覧を protocol からではなくて適当なYAMLファイルから読む仕様に変更したいです
