### ISSUE TITLE
Database description is wrong

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/dataware-tools#58]
## Purpose
Bug report

## Description
データセット一覧の `Description` の部分に名前が表示されている

## Screenshot or video [Optional]
<img width="1466" alt="スクリーンショット 2021-07-26 16 20 39" src="https://user-images.githubusercontent.com/24401842/126948879-aaa14d47-821c-4979-b933-f5a3bb40e358.png">

**Comment by d-hayashi** [comment]
@WatanabeToshimitsu 
すいません、さっきレビューを通してしまったのですが、バグがありました。。

↓の `param.row.name` になっている部分が原因かと思われます
https://github.com/dataware-tools/app-data-browser-next/blob/5e6fbcb5ffe7e6b7825b701390e1e68c5098d155/src/components/organisms/DatabaseList.tsx#L73

**Comment by WatanabeToshimitsu** [comment]
https://github.com/dataware-tools/app-data-browser-next/pull/101/files#diff-4719b57c5cb80f24a6dcca98139f60a5254e8110c599f4613aa24c0dd96fed62R141
僕もついさっき気づいて，↑ でサクッと直しちゃいました

**Comment by d-hayashi** [comment]
あざます！

**Comment by hdl-service** [comment]
@d-hayashi: Closing this issue.

<details>

In response to [this](https://github.com/dataware-tools/dataware-tools/issues/58#issuecomment-886449236):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
