### ISSUE TITLE
[Data-browser] Show details of a database problem

### ISSUE THREAD

**Issue by sudach** [dataware-tools/dataware-tools#63]
## Purpose
- Feature request

## Description
If there is a problem with the database, the details of the problem need to be displayed.

Describe the issue  
Example:
- Video preview does not work

## System info [Optional]
Client environment
- OS: Mac OS (M1)
- Browser: Google Chrome 92.0.4515.107（Official Build） （arm64）

DB environment
- META_DB_ENGINE: mongodb

## Screenshot or video [Optional]
<img width="726" alt="スクリーンショット 2021-07-29 15 21 19" src="https://user-images.githubusercontent.com/47210083/127444365-32a70f67-8c83-4a22-b3c3-37b172362132.png">

**Comment by sudach** [comment]
Because of the backend problem, it would be better to only display something like "Something went wrong in the server. Please contact the administrator".

**Comment by hdl-service** [comment]
@d-hayashi: Closing this issue.

<details>

In response to [this](https://github.com/dataware-tools/dataware-tools/issues/63#issuecomment-903517735):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
