### ISSUE TITLE
[Data-browser, User-manager] Fix stories not to depend on authentication

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#67]
## Purpose
- Feature request

## Description
- To introduce visual regression test,  we should fix stories not to depend on authentication. Because loki (visual regression testing tool for storybook) can't use authentication information for security reason.
- Furthermore, test depending authentication generally have low testability.

ビジュアルリグレッションテストを導入するために，各story を認証に依存しないようにする必要があります．というのも，loki (storybook 用のビジュアルリグレッションテストツール）は認証情報をセキュリティ上の理由で利用できないからです．
また，認証に依存するようなテストは一般にテスト容易性が低い傾向にあります．

## See also
- Related https://github.com/dataware-tools/dataware-tools/issues/61

**Comment by d-hayashi** [comment]
v0.2.1 で一部のコンポーネントがLokiでテストできるようにすべし

**Comment by WatanabeToshimitsu** [comment]
Done!!
See
- https://github.com/dataware-tools/app-template-nextjs/pull/35
- https://github.com/dataware-tools/app-common/pull/89
- https://github.com/dataware-tools/app-data-browser-next/pull/133
- https://github.com/dataware-tools/app-user-manager/pull/109
