### ISSUE TITLE
[Data-browser, User-manager] Show error message as toast

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#68]
## Purpose
- feature request

## Description
- Error message which is shown as exchanged from original UI may decrease UX, so almost all error message should be shown as toast.

## See also
- https://github.com/fkhadra/react-toastify
- https://next.material-ui.com/components/snackbars/

**Comment by d-hayashi** [comment]
Toastと今までの様なエラー表示を併用するのが理想的
1. ユーザにとって重要なエラー（操作を止めないといけないようなエラー）は今までと同様に表示
2. ユーザにとってあまり重要ではない通知 (Succeededとか) はToastで表示

**Comment by WatanabeToshimitsu** [comment]
Resolved by https://github.com/dataware-tools/app-data-browser-next/pull/485 and https://github.com/dataware-tools/app-user-manager/pull/367
