### ISSUE TITLE
[app-common] Material-UI のシステムに乗っかる

### ISSUE THREAD

**Issue by d-hayashi** [dataware-tools/dataware-tools#7]
## Description
Material UI に最初から入っているコンポーネントをできるだけ使うようにする
[https://next.material-ui.com/system/basics/](https://next.material-ui.com/system/basics/)

**Comment by WatanabeToshimitsu** [comment]
This issue Relate to https://github.com/dataware-tools/dataware-tools/issues/70, because Material-UI v5 recommend to use "system" to determine style of UI

**Comment by d-hayashi** [comment]
Closing in favor of #70

**Comment by hdl-service** [comment]
@d-hayashi: Closing this issue.

<details>

In response to [this](https://github.com/dataware-tools/dataware-tools/issues/7#issuecomment-903572821):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
